export default interface FilteredPropertyData {
    bathrooms: number,
    bedrooms: number,
    city: string,
    country: string,
    // currency: 'USD',
    // daysOnZillow: -1,
    homeStatus: string,
    // homeStatusForHDP: 'FOR_SALE',
    homeType: string,
    imgSrc: string,
    // isFeatured: false,
    // isNonOwnerOccupied: true,
    // isPreforeclosureAuction: false,
    // isPremierBuilder: false,
    // isShowcaseListing: false,
    isUnmappable: boolean,
    // isZillowOwned: boolean,
    latitude: number,
    // listing_sub_type: { is_FSBA: true },
    livingArea: number,
    longitude: number,
    lotAreaUnit: string,
    lotAreaValue: number,
    price: number,
    priceForHDP: number,
    rentZestimate: number,
    // shouldHighlight: boolean,
    state: string,
    streetAddress: string,
    taxAssessedValue: number,
    zestimate: number,
    zipcode: string,
    zpid: number
}