export class SearchPropertyResponseDto {
    bathrooms: number;
    bedrooms: number;
    city: string;
    country: string;
    currency: string;
    daysOnZillow: number;
    homeStatus: string;
    homeStatusForHDP: string;
    homeType: string;
    imgSrc: string;
    isFeatured: boolean;
    isNonOwnerOccupied: boolean;
    isPreforeclosureAuction: boolean;
    isPremierBuilder: boolean;
    isShowcaseListing: boolean;
    isUnmappable: boolean;
    isZillowOwned: boolean;
    latitude: number;
    listing_sub_type: { is_FSBA: boolean };
    livingArea: number;
    longitude: number;
    lotAreaUnit: string;
    lotAreaValue: number;
    price: number;
    priceForHDP: number;
    rentZestimate: number;
    shouldHighlight: boolean;
    state: string;
    streetAddress: string;
    taxAssessedValue: number;
    zestimate: number;
    zipcode: string;
    zpid: number;
}